# Generated by Django 5.0.6 on 2024-12-02 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('Nature', models.CharField(max_length=50)),
                ('Charge', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('capacite', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('specialisation', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=50)),
                ('date_embauche', models.DateField()),
                ('departementID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.departement')),
            ],
        ),
        migrations.CreateModel(
            name='AffectationCours',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ChargeEdu', models.PositiveIntegerField()),
                ('AU', models.CharField(max_length=10)),
                ('Semestre', models.PositiveIntegerField()),
                ('enseignant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.enseignant')),
                ('Matieres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=100)),
                ('Departement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.departement')),
            ],
        ),
        migrations.AddField(
            model_name='matiere',
            name='Parcours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.parcours'),
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('annee_academique', models.CharField(max_length=10)),
                ('Parcours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.parcours')),
            ],
        ),
        migrations.CreateModel(
            name='EmploiCours',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jour', models.CharField(max_length=20)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('classe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.classe')),
                ('enseignant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.enseignant')),
                ('Matiere_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.matiere')),
                ('salle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.salle')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=128)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.role')),
            ],
        ),
        migrations.CreateModel(
            name='LogModification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=200)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField()),
                ('utilisateur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='InscriptionClasse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_inscription', models.DateField()),
                ('classe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.classe')),
                ('etudiant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.utilisateur')),
            ],
        ),
        migrations.AddField(
            model_name='departement',
            name='Directeur_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_admin.utilisateur'),
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('justifie', models.BooleanField(default=False)),
                ('motif', models.TextField(blank=True, null=True)),
                ('Emploi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.emploicours')),
                ('etudiant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='app_admin.utilisateur')),
            ],
        ),
    ]
