# Generated by Django 5.0.6 on 2024-12-02 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emploicours',
            old_name='classe_id',
            new_name='classe',
        ),
        migrations.RenameField(
            model_name='emploicours',
            old_name='enseignant_id',
            new_name='enseignant',
        ),
        migrations.RenameField(
            model_name='emploicours',
            old_name='Matiere_id',
            new_name='matiere',
        ),
        migrations.RenameField(
            model_name='emploicours',
            old_name='salle_id',
            new_name='salle',
        ),
    ]
